export const authCopy = {
  login: {
    title: 'Đăng nhập',
    description: 'Dùng tài khoản được cấp quyền để truy cập EduHealth.',
    identifierLabel: 'Tên đăng nhập',
    passwordLabel: 'Mật khẩu',
    identifierPlaceholder: 'Nhập username',
    passwordPlaceholder: 'Nhập mật khẩu',
    remember: 'Ghi nhớ đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    submit: 'Đăng nhập',
    submitting: 'Đang xử lý...',
    genericError: 'Đăng nhập thất bại. Vui lòng thử lại.',
    invalidIdentifier: 'Vui lòng nhập tên đăng nhập.',
    invalidPassword: 'Vui lòng nhập mật khẩu.',
  },
  forgotPassword: {
    title: 'Quên mật khẩu',
    description: 'Nhập email đã đăng ký để nhận mã xác thực.',
    identifierLabel: 'Email đăng ký',
    identifierPlaceholder: 'name@school.edu',
    submit: 'Gửi mã xác thực',
    submitting: 'Đang gửi...',
    backToLogin: 'Quay lại đăng nhập',
    invalidEmail: 'Email chưa đúng định dạng.',
    notFoundEmail: 'Email không tồn tại trong hệ thống.',
  },
  verifyOtp: {
    title: 'Nhập mã OTP',
    description: 'Nhập mã 6 số đã gửi đến email của bạn.',
    otpLabel: 'Mã xác thực',
    submit: 'Xác nhận và tiếp tục',
    submitting: 'Đang xác nhận...',
    resendPrompt: 'Không nhận được mã?',
    resendAction: 'Gửi lại mã',
    resendCountdownPrefix: 'Gửi lại mã sau',
    resendCountdownSuffix: 'giây',
    invalidCode: 'Mã OTP không hợp lệ hoặc đã hết hạn.',
    missingIdentifier: 'Phiên xác thực không hợp lệ. Vui lòng nhập email lại từ bước trước.',
    sentToLabel: 'Mã xác thực đã gửi đến',
    editEmailAction: 'Đổi email nhận mã',
    resendLoading: 'Đang gửi lại...',
  },
  changePassword: {
    title: 'Tạo mật khẩu mới',
    description: 'Thiết lập mật khẩu mới.',
    newPasswordLabel: 'Mật khẩu mới',
    confirmPasswordLabel: 'Xác nhận mật khẩu',
    newPasswordPlaceholder: 'Nhập mật khẩu mới',
    confirmPasswordPlaceholder: 'Nhập lại mật khẩu mới',
    submit: 'Cập nhật mật khẩu',
    submitting: 'Đang cập nhật...',
    backToLogin: 'Quay lại đăng nhập',
    mismatchedPassword: 'Mật khẩu xác nhận chưa khớp.',
    invalidPassword: 'Mật khẩu mới chưa đáp ứng đủ điều kiện bảo mật.',
    successMessage: 'Mật khẩu đã được cập nhật. Bạn có thể đăng nhập lại.',
    invalidSession: 'Phiên đặt lại mật khẩu không hợp lệ. Vui lòng thực hiện lại từ bước nhận OTP.',
    rules: [
      'Tối thiểu 8 ký tự',
      'Ít nhất 1 chữ in hoa',
      'Ít nhất 1 chữ số',
      'Ít nhất 1 ký tự đặc biệt',
    ],
  },
};
