export const authCopy = {
  login: {
    title: 'Chào mừng trở lại',
    description: 'Vui lòng nhập thông tin để truy cập hệ thống sức khỏe học đường',
    identifierLabel: 'Email hoặc Tên đăng nhập',
    passwordLabel: 'Mật khẩu',
    remember: 'Ghi nhớ đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    submit: 'Đăng nhập',
    submitting: 'Đang xử lý...',
    createAccountPrompt: 'Bạn là người mới?',
    createAccountAction: 'Tạo tài khoản ngay',
    genericError: 'Đăng nhập thất bại. Vui lòng thử lại.',
  },
  forgotPassword: {
    title: 'Quên mật khẩu',
    description: 'Nhập email hoặc tên đăng nhập để nhận mã OTP xác thực tài khoản của bạn.',
    identifierLabel: 'Email hoặc Tên đăng nhập',
    submit: 'Gửi mã OTP',
    submitting: 'Đang gửi...',
    backToLogin: 'Quay lại trang đăng nhập',
    supportPrompt: 'Bạn cần hỗ trợ?',
    supportAction: 'Liên hệ bộ phận CNTT',
  },
  verifyOtp: {
    title: 'Xác thực mã OTP',
    description: 'Vui lòng nhập mã xác thực 6 chữ số vừa được gửi đến thiết bị của bạn.',
    submit: 'Xác nhận',
    resendPrompt: 'Bạn không nhận được mã?',
    resendAction: 'Gửi lại mã',
    supportAction: 'Cần hỗ trợ kỹ thuật?',
    securityCaption: 'Mã hóa đầu cuối EduHealth',
  },
  changePassword: {
    title: 'Đặt lại mật khẩu',
    description: 'Vui lòng nhập mật khẩu mới để bảo vệ tài khoản của bạn.',
    newPasswordLabel: 'Mật khẩu mới',
    confirmPasswordLabel: 'Xác nhận mật khẩu',
    submit: 'Cập nhật',
    backToLogin: 'Quay lại đăng nhập',
    supportDescription: 'Nếu bạn gặp khó khăn trong quá trình đổi mật khẩu, vui lòng liên hệ bộ phận',
    supportAction: 'Hỗ trợ kỹ thuật',
    rules: [
      'Tối thiểu 8 ký tự',
      'Có chữ in hoa',
      'Có chữ số',
      'Ký tự đặc biệt',
    ],
  },
};
