export const authCopy = {
  login: {
    title: 'Đăng nhập hệ thống',
    description: 'Dùng tài khoản do nhà trường cấp để truy cập.',
    identifierLabel: 'Email hoặc Tên đăng nhập',
    passwordLabel: 'Mật khẩu',
    remember: 'Ghi nhớ đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    submit: 'Đăng nhập',
    submitting: 'Đang xử lý...',
    supportPrompt: 'Cần hỗ trợ truy cập?',
    supportAction: 'Liên hệ quản trị viên.',
    genericError: 'Đăng nhập thất bại. Vui lòng thử lại.',
  },
  forgotPassword: {
    title: 'Khôi phục mật khẩu',
    description: 'Nhập email hoặc tên đăng nhập để nhận mã OTP.',
    identifierLabel: 'Email hoặc Tên đăng nhập',
    submit: 'Gửi mã OTP',
    submitting: 'Đang gửi...',
    backToLogin: 'Quay lại đăng nhập',
    supportPrompt: 'Không nhận được mã?',
    supportAction: 'Liên hệ bộ phận CNTT.',
  },
  verifyOtp: {
    title: 'Nhập mã OTP',
    description: 'Nhập 6 số đã gửi đến email của bạn.',
    submit: 'Xác nhận mã',
    submitting: 'Đang xác nhận...',
    resendPrompt: 'Không nhận được mã?',
    resendAction: 'Gửi lại mã',
    supportPrompt: 'Không nhận được mã?',
    supportAction: 'Kiểm tra email hoặc liên hệ hỗ trợ.',
    invalidCode: 'Vui lòng nhập đủ 6 chữ số OTP.',
  },
  changePassword: {
    title: 'Đặt lại mật khẩu',
    description: 'Tạo mật khẩu mới cho tài khoản của bạn.',
    newPasswordLabel: 'Mật khẩu mới',
    confirmPasswordLabel: 'Xác nhận mật khẩu',
    submit: 'Cập nhật mật khẩu',
    submitting: 'Đang cập nhật...',
    backToLogin: 'Quay lại đăng nhập',
    supportPrompt: 'Cần hỗ trợ truy cập?',
    supportAction: 'Liên hệ bộ phận CNTT.',
    mismatchedPassword: 'Mật khẩu xác nhận chưa khớp.',
    invalidPassword: 'Mật khẩu chưa đáp ứng đủ điều kiện.',
    rules: [
      'Tối thiểu 8 ký tự',
      'Có chữ in hoa',
      'Có chữ số',
      'Ký tự đặc biệt',
    ],
  },
};
